Refactor/clean data fetching
okp4/portal-web pull request #135
Opened 2022-11-29 15:42 UTC by RaphaelEscrig

This PR refactor all [data fetching](https://nextjs.org/docs/basic-features/data-fetching/overview) for all pages.

Because we have a few data and they are all mocked, no cache revalidation has been set. In a near future, when we will connect the portal to an api, a cache validation is needed.

Feel free to discuss about this implementation !

2022-11-30 13:06 UTC, ErikssonJoakim commented
Am I correct to assume that we will need to change the `getStaticProps` for `getServerSideProps` once the api is up and running? @RaphaelEscrig

2022-11-30 13:23 UTC, RaphaelEscrig commented
Not necessarily; `getStaticProps` can be used to fetch external data too. `getServerSideProps` is useful if we want to render a page with data fetched at request time.

With `getStaticProps`, on build time, the page will be cached which is not the default case with `getServerSideProps`.

[Here](https://webkul.com/blog/getstaticprops-vs-getserversideprops-next-js-data-fetching/) is an article explaining the differences between these two methods.

2022-11-30 13:51 UTC, ErikssonJoakim requested changes

2022-11-30 13:51 UTC, ErikssonJoakim commented on environment.d.ts
>      OKP4_DISCORD_URL: string
The social media urls + website do not work, they need to be made public like the navigation variables. I have not tested the other variables

2023-01-25 12:25 UTC, ErikssonJoakim commented
Seeing as we've reworked the api I suggest we close this PR @fredericvilcot

2023-01-26 15:36 UTC, closed without merging