feat: redirect homepage datasets entities to dataset page on click
okp4/portal-web pull request #188
Opened 2023-01-23 14:25 UTC by ErikssonJoakim

This PR adds a redirect for the dataset entities in the home page to their respective page

2023-01-23 15:01 UTC, ccamel approved these changes
:+1:

2023-01-25 14:24 UTC, fredericvilcot requested changes

2023-01-25 14:24 UTC, fredericvilcot commented on src/components/dataspaceDashboard/dataspaceEntities/DataspaceEntities.tsx
> +            <Card
You can refactor this lines of code as you repeat yourself twice with the `Card` component.

2023-01-25 14:24 UTC, fredericvilcot commented on src/components/dataspaceDashboard/dataspaceEntities/dataspaceEntities.scss
> +    a {
You can put this rule at the top level to prevent from repeating yourself

2023-01-25 15:18 UTC, ErikssonJoakim commented
Thank you for your feedback 🙂 👍  I have refactored the code as suggested

2023-01-25 15:45 UTC, fredericvilcot approved these changes
👌

2023-01-25 15:52 UTC, merged