feat: add explore layout with fake data
okp4/portal-web pull request #28
Opened 2022-09-22 13:09 UTC by RaphaelEscrig

This PR aims to implement the _explore_ page of the portal.
Please have a look at this issue for more details: https://github.com/okp4/portal-web/issues/26

URL to test: http://localhost:3000/explore

The build is not working because it needs the ui with the last List / ListItem version. In order to test this PR, you need to manually add the good version of the lib.

👉 As it is not possible to disable SSR for the whole page, we had to split the page into sub-components in order to disable SSR each time a document was used.

2022-10-12 09:55 UTC, JoeyDjr requested changes
LGTM, juste a remark

2022-10-12 09:55 UTC, JoeyDjr commented on src/components/explore/exploreList/ExploreList.tsx
> +      router.push(`/dataspace/${item.dataspaceId}/${item.type}/${item.id}`)
You can remove this unnecessary `return`
```suggestion
      if (item.type === 'dataspace') {
        router.push(`/dataspace/${item.dataspaceId}`)
      } else {
        router.push(`/dataspace/${item.dataspaceId}/${item.type}/${item.id}`)
      }
```

2022-10-12 12:59 UTC, ErikssonJoakim requested changes
Got some last minute remarks, otherwise it looks good to me :)

2022-10-12 12:59 UTC, ErikssonJoakim commented on src/pages/api/fake/explore/index.ts
> +const handler = (req: NextApiRequest, res: NextApiResponse): void => {
No need to disable the linter here, parameters can be readonly

2022-10-12 12:59 UTC, ErikssonJoakim commented on src/components/pageTitle/pageTitle.scss
> +  @media screen and (max-width: 1300px) {
Imo the title should be centered when filter moves above the list. Same for the list configuration.

It looks weird to have the config and title not centered when the list is.

2022-10-13 07:20 UTC, JoeyDjr approved these changes

2022-10-17 09:51 UTC, fredericvilcot commented
@RaphaelEscrig 
We can't review this PR as the Ci fails.
Thanks

2022-10-17 09:52 UTC, RaphaelEscrig commented
>

2022-10-19 09:57 UTC, closed without merging